version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data
      - ./backend/.env:/app/.env
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key}
    command: >
      bash -c "apt-get update && apt-get install -y curl && 
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ../../
      dockerfile: examples/langchain/frontend/Dockerfile
      target: frontend-builder
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    ports:
      - "127.0.0.1:5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    working_dir: /app/frontend
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

volumes:
  data: 