# generated by datamodel-codegen:
#   filename:  types.json
#   timestamp: 2025-03-05T11:08:48+00:00

from __future__ import annotations

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Model(RootModel[Any]):
    root: Any


class Metadata(BaseModel):
    """
    key convention to hide from display _key

    If type='pdf', you can set the 'page' and '_page' properties to specify the page number to display in the ContentDisplay component.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    page: Annotated[Optional[int], Field(ge=1, title='page')] = None
    """
    The page number to display for PDF documents. Page numbers are 1-based.
    """
    field_page: Annotated[Optional[int], Field(alias='_page', ge=1, title='_page')] = (
        None
    )
    """
    Hidden from display. The page number to display for PDF documents. Page numbers are 1-based.
    """


class ArrayBufferLike(RootModel[Any]):
    root: Any


class PDFHighlight(RootModel[Any]):
    root: Any


class UUID(RootModel[Any]):
    root: Any


class Message(BaseModel):
    """
    Represents a chat message in the conversation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='id')]
    role: Annotated[Literal['assistant', 'user'], Field(title='role')]
    content: Annotated[str, Field(title='content')]


class Data(BaseModel):
    """
    Optional data to display in the ContentDisplay component. This can be set initially
    or lazily loaded when the \`SET_SELECTED_SOURCE\` action is handled. Simply return the data
    from your \`onAction()\` function as \`sourceData\` in the response.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    BYTES_PER_ELEMENT: Annotated[float, Field(title='BYTES_PER_ELEMENT')]
    buffer: Annotated[ArrayBufferLike, Field(title='buffer')]
    byteLength: Annotated[float, Field(title='byteLength')]
    byteOffset: Annotated[float, Field(title='byteOffset')]
    length: Annotated[float, Field(title='length')]
    field___toStringTag_23: Annotated[
        Literal['Uint8Array'],
        Field(alias='__@toStringTag@23', title='__@toStringTag@23'),
    ] = 'Uint8Array'


class Source(BaseModel):
    """
    Represents a source of information that can be displayed and referenced.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(title='id')]
    title: Annotated[str, Field(title='title')]
    """
    Title of the source displayed in the SourcesDisplay component.
    """
    type: Annotated[Literal['html', 'markdown', 'pdf', 'text'], Field(title='type')]
    """
    Type of the source, used to determine the type of data to display in the ContentDisplay component.
    """
    description: Annotated[Optional[str], Field(title='description')] = None
    """
    Description of the source displayed in the SourcesDisplay component if provided.
    """
    relevance: Annotated[Optional[float], Field(title='relevance')] = None
    """
    Relevance score of the source. It is displayed in the SourcesDisplay component as bar chart.
    """
    href: Annotated[Optional[str], Field(title='href')] = None
    """
    Optional href to display a link to the source in the SourcesDisplay component.
    """
    data: Annotated[Optional[Union[Data, str]], Field(title='data')] = None
    """
    Optional data to display in the ContentDisplay component. This can be set initially
    or lazily loaded when the \`SET_SELECTED_SOURCE\` action is handled. Simply return the data 
    from your \`onAction()\` function as \`sourceData\` in the response.
    """
    metadata: Annotated[Optional[Metadata], Field(title='metadata')] = None
    """
    key convention to hide from display _key

    If type='pdf', you can set the 'page' and '_page' properties to specify the page number to display in the ContentDisplay component.
    """
    highlights: Annotated[Optional[List[PDFHighlight]], Field(title='highlights')] = (
        None
    )
    """
    Highlight annotations in the PDF document. Only applicable for PDF sources.
    """


class StreamChunk(BaseModel):
    """
    Represents a chunk of streamed content.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    content: Annotated[Optional[str], Field(title='content')] = None
    sources: Annotated[Optional[List[Source]], Field(title='sources')] = None
    done: Annotated[Optional[bool], Field(title='done')] = None
